[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "uvaml1-math"
authors = [{name = "Floor Eijkelboom", email = "eijkelboommfloor@gmail.com"}]
dynamic = ["version", "description"]
